version: '3.8'

networks:
  sw_network:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: smartwallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - sw_network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init-db.sql

  app:
    build: .
    container_name: smartwallet-app
    image: smartwallet:latest
    networks:
      - sw_network
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/smartwallet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
volumes:
  pgdata:
